// Regenerates src/merge/lib/robinhoodAssets.generated.ts -- the assets the
// Launch form offers on Robinhood Chain.
//
//   npx tsx scripts/generate-robinhood-assets.mts
//
// Discovery is entirely on-chain, so the list is what actually trades rather
// than anything hand-maintained:
//   1. every Uniswap v3 pool paired with USDG (PoolCreated logs, both slots),
//   2. read name/symbol/decimals of each counterparty through Multicall3,
//   3. keep the ones Robinhood issues -- their name ends "• Robinhood Token".
// USDG (the cash leg) and WETH are added explicitly.
//
// Run it again when Robinhood lists new stock tokens; it is a static list on
// purpose, because doing this walk in the browser would be thousands of calls
// per page load.
import { createPublicClient, http, defineChain, parseAbiItem, parseAbi, getAddress } from "viem";
import { writeFileSync } from "node:fs";

const realFetch = globalThis.fetch;
// Robinhood's public RPC rejects default runtime user agents.
globalThis.fetch = (i: Parameters<typeof realFetch>[0], init: Parameters<typeof realFetch>[1] = {}) =>
  realFetch(i, { ...init, headers: { ...(init as { headers?: Record<string, string> }).headers, "user-agent": "Mozilla/5.0" } });

const chain = defineChain({
  id: 4663,
  name: "Robinhood Chain",
  nativeCurrency: { name: "Ether", symbol: "ETH", decimals: 18 },
  rpcUrls: { default: { http: ["https://rpc.mainnet.chain.robinhood.com"] } },
  contracts: { multicall3: { address: "0xcA11bde05977b3631167028862bE2a173976CA11" } },
});
const pc = createPublicClient({ chain, transport: http(undefined, { batch: true }), batch: { multicall: { batchSize: 512 } } });

const V3_FACTORY = "0x1f7d7550b1b028f7571e69a784071f0205fd2efa";
const USDG = "0x5fc5360D0400a0Fd4f2af552ADD042D716F1d168";
const WETH = "0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73";
const POOL_CREATED = parseAbiItem(
  "event PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)",
);
const ERC20 = parseAbi([
  "function name() view returns (string)",
  "function symbol() view returns (string)",
  "function decimals() view returns (uint8)",
]);

const head = await pc.getBlockNumber();
const counterparties = new Set<string>();
for (const slot of ["token0", "token1"] as const) {
  let from = 0n;
  const STEP = 5_000_000n; // the public RPC refuses the whole range in one call
  while (from <= head) {
    const to = from + STEP > head ? head : from + STEP;
    const logs = await pc.getLogs({ address: V3_FACTORY, event: POOL_CREATED, args: { [slot]: USDG } as never, fromBlock: from, toBlock: to });
    for (const l of logs) {
      const other = slot === "token0" ? l.args.token1 : l.args.token0;
      if (other) counterparties.add(getAddress(other));
    }
    from = to + 1n;
  }
}

const all = [...counterparties];
const assets: { address: string; symbol: string; name: string; decimals: number }[] = [];
for (let i = 0; i < all.length; i += 150) {
  const slice = all.slice(i, i + 150);
  const res = await pc.multicall({
    contracts: slice.flatMap((a) => [
      { address: a as `0x${string}`, abi: ERC20, functionName: "name" },
      { address: a as `0x${string}`, abi: ERC20, functionName: "symbol" },
      { address: a as `0x${string}`, abi: ERC20, functionName: "decimals" },
    ] as const),
    allowFailure: true,
  });
  slice.forEach((a, k) => {
    const name = res[k * 3].result as string | undefined;
    const symbol = res[k * 3 + 1].result as string | undefined;
    const decimals = res[k * 3 + 2].result as number | undefined;
    if (name && symbol && decimals !== undefined && /Robinhood Token/i.test(name)) {
      assets.push({ address: a, symbol, name, decimals: Number(decimals) });
    }
  });
}
assets.sort((a, b) => a.symbol.localeCompare(b.symbol));

const issuer = (name: string) => name.replace(/\s*[•·]\s*Robinhood Token\s*$/i, "").trim();
const file = `// GENERATED by scripts/generate-robinhood-assets.mts -- do not edit by hand.
// Discovered on-chain ${new Date().toISOString().slice(0, 10)}: every token with a Uniswap v3
// pool against USDG whose name marks it a Robinhood stock token, plus the
// cash leg and WETH. Re-run the script when new tokens list.
import type { AssetRef } from "./evmChain";

export const ROBINHOOD_ASSETS: AssetRef[] = [
  { address: "${USDG}", symbol: "USDG", decimals: 6, note: "Global Dollar — the cash leg" },
  { address: "${WETH}", symbol: "WETH", decimals: 18, note: "Wrapped Ether" },
${assets.map((a) => `  { address: "${a.address}", symbol: ${JSON.stringify(a.symbol)}, decimals: ${a.decimals}, note: ${JSON.stringify(issuer(a.name))} },`).join("\n")}
];
`;
writeFileSync(new URL("../src/merge/lib/robinhoodAssets.generated.ts", import.meta.url), file);
console.log(`wrote ${assets.length} stock tokens (+ USDG, WETH)`);
